sudo: required
dist: trusty
language: node_js
node_js:
  - '10'
addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g makeshift && makeshift -s @systelab-technologies -r https://registry.npmjs.org
  - npm install -g codecov
  - npm install -g codacy-coverage
  - npm install

script:
  - ng build systelab-translate --prod
  - ng test systelab-translate --watch=false --code-coverage

after_success:
  - cat coverage/lcov.info | codecov
  - cat ./coverage/lcov.info | codacy-coverage

before_deploy:
  - cd dist/systelab-translate

deploy:
  skip_cleanup: true
  provider: npm
  email: aserra@werfen.com
  api_key: $NPM_TOKEN
  on:
    tags: true
