sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g codecov
  - npm install -g codacy-coverage
  - npm install
  - ng build

script: 
  - ng test --single-run --code-coverage

after_success:
  - cat coverage/lcov.info | codecov
  - cat ./coverage/lcov.info | codacy-coverage
