sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g codecov
  - npm install -g codacy-coverage
  - npm install
  - ng build

script: 
  - ng test --single-run --code-coverage

after_success:
  - cat coverage/lcov.info | codecov -t 2b1d7f78-2aa5-4cff-bbf4-e6ff70650d92
  - cat coverage/lcov.info | codacy-coverage --accountToken a56328c9eaf148ff950960814e904fa5 --username systelab --projectName systelab-translate
